---
- hosts: web
  become: yes
  vars:
    - root_db_password: 123
    - mmuser_password: "123"
    - mm_user: "mmuser"
    - mattermost_db: "mattermost"
    - hostname: "localhost"
  gather_facts: true

  tasks:
       
    - name: Set MySQL root password before installing
      # become: yes
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{root_db_password | quote}}' vtype='password'

    - name: Confirm MySQL root password before installing
      # become: yes
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{root_db_password | quote}}' vtype='password'

    - name: Install packages | pip | mysqldb | mysql-server
      # become: yes
      apt: name={{ item }} state=latest
      with_items:
        - python-pip
        - python3-pip
        - python-mysqldb
        - mysql-server
    
    - name: Install the Python MySQLB module
      pip: name=PyMySql

    - name: copy .my.cnf file with root credentials
      template: src=templates/.my.cnf dest={{ ansible_env.HOME}}/.my.cnf owner=root mode=0744
    
    - name: Create a new database
      mysql_db:
        name: mattermost
        state: present    

    - name: Creating mysql user
      mysql_user:
        name: "{{mm_user}}"
        password: "{{ mmuser_password }}"
        priv: '{{ mattermost_db }}.*:ALL'
        state: present
    
    - name: Download mattermost
      # become: yes
      get_url:
        url: https://releases.mattermost.com/5.7.1/mattermost-5.7.1-linux-amd64.tar.gz
        dest: /opt
        mode: 0744
  
    - name: Extract
      # become: yes 
      unarchive:
        src: /opt/mattermost-5.7.1-linux-amd64.tar.gz
        dest: /opt
        remote_src: yes
    
    - name: Creating directory 
      file:
        path: /opt/mattermost/data
        state: directory

    - name: Create user group named Mattermost
      group:
        name: mattermost
        state: present

    - name: Create system user named Mattermost
      user:
        name: mattermost
        system: yes
        group: mattermost 

    - name: Setup permissions for user and groups  
      file: 
        path: /opt/mattermost/
        owner: mattermost
        group: mattermost
        mode: 0744
        recurse: yes

    - name: Updating config.json
      lineinfile:
        path: /opt/mattermost/config/config.json
        regexp: '(?:"DataSource": "mmuser:)'
        line:  '"DataSource": "mmuser:{{ mmuser_password }}@tcp({{ hostname }}:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s",'
        mode: 0744
        backup: yes

