---
- hosts: web
  become: yes
  gather_facts: true

  tasks:
    - name: Download mattermost
      get_url:
        url: https://releases.mattermost.com/5.7.1/mattermost-5.7.1-linux-amd64.tar.gz
        dest: /opt
        mode: 0744
  
    - name: Extract
      unarchive:
        src: /opt/mattermost-5.7.1-linux-amd64.tar.gz
        dest: /opt
        remote_src: yes
    
    - name: Creating directory 
      file:
        path: /opt/mattermost/data
        state: directory

    - name: Create user group named Mattermost
      group:
        name: mattermost
        state: present

    - name: Create system user named Mattermost
      user:
        name: mattermost
        system: yes
        group: mattermost 

    - name: Setup permissions for user and groups  
      file: 
        path: /opt/mattermost/
        owner: mattermost
        group: mattermost
        mode: 0744
        recurse: yes

    - name: Updating config.json
      lineinfile:
        path: /opt/mattermost/config/config.json
        regexp: '(?:"DataSource": "mmuser:)'
        line:  '"DataSource": "mmuser:{{ mmuser_password }}@tcp({{ hostname }}:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s",'
        mode: 0744
        backup: yes
        
    - name: Mattermost | Create UNIT file
      template: src=templates/mattermost.service dest=/lib/systemd/system/ mode=0744

    - name: Start Mattermost server
      systemd:
        name: mattermost
        daemon_reload: yes
        enabled: yes
        state: started
